### ISSUE TITLE
Validate username: add character limit to prevent overflow

### ISSUE THREAD

**Issue by fibanneacci** [fibanneacci/liar#9]

**Comment by fibanneacci** [comment]
In addition to checking this condition, it would probably be good to add an informative error message (you can modify the current one, which only displays the "alphanumeric" requirement)

**Comment by mdPial** [comment]
I would like to work on that. To work further I need to know about the max character limit!!

**Comment by fibanneacci** [comment]
Awesome, thanks! And yup, it's your choice! (If you want, you can also change the CSS to make the font smaller)

**Comment by mdPial** [comment]
Welcome!. I have a question. Do you want to prevent this overflow? 
![image](https://user-images.githubusercontent.com/43095489/106855648-77e66b00-66e7-11eb-86a8-4ff288ed26f7.png)

**Comment by fibanneacci** [comment]
Yeah! Ideally everything should fit neatly into the box. Also if you have other ideas for how to implement this (besides character limit / font size / some combination of different methods) feel free to take it in whatever direction you want!

**Comment by mdPial** [comment]
Okay. Thanks for the detailed explanation. 😀
